In [1]:
#Exercise 1. Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.24.3


In [6]:
#Exercise 2. How to create a 1D array?
X = np.arange(10)
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Exercise 3. How to create a boolean array?
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
#Exercise 4. How to extract items that satisfy a given condition from 1D array?
arr = np.arange(10)

arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [5]:
#Exercise 5. How to replace items that satisfy a condition with another value in numpy array?
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
#Exercise 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(10)
out = arr.copy()
out[out%2 == 1] = -1
print('Modified Array')
print(out)
print('\nOriginal Array')
print(arr)


Modified Array
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array
[0 1 2 3 4 5 6 7 8 9]


In [8]:

#Exercise 7. How to reshape an array?
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
#Exercise 8. How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
#Exercise 9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
#Exercise 10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
print(np.repeat(a,3))
print(np.tile(a,3))
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
#Exercise 11. How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [13]:
#Exercise 12. How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [14]:
#Exercise 13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [15]:
#Exercise 14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [16]:
#Exercise 15. How to make a python function that handles scalars to work on numpy arrays?
def square_scalar(x):
    """Function to square a scalar."""
    return x ** 2

square_vectorized = np.vectorize(square_scalar)
array = np.array([1, 2, 3, 4, 5])
result = square_vectorized(array)
print(result)

[ 1  4  9 16 25]


In [17]:
#Exercise 16. How to swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)

print('Original array')
print(arr)
print("\nModified array")
print(arr[:, [1,0,2]])

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [18]:
#Exercise 17. How to swap two rows in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)
print("\nModified array")
print(arr[[1,0,2], :])

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [19]:
#Exercise 18. How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)
print("\nModified array")
print(arr[::-1, :])

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [20]:
#Exercise 19. How to reverse the columns of a 2D array?
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)
print("\nModified array")
print(arr[:,::-1])

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [21]:
#Exercise 20. How to create a 2D array containing random floats between 5 and 10?
rand_arr = np.random.uniform(5,10, size=(2,3))
rand_arr

array([[6.27566136, 6.31365433, 6.92747049],
       [6.7312473 , 5.42269676, 8.65906905]])

In [22]:
#Exercise 21. How to print only 3 decimal places in python numpy array?
rand_arr = np.random.random((2,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.653, 0.747, 0.54 ],
       [0.149, 0.385, 0.251]])

In [23]:
#Exercise 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
arr = np.array([1e10, 2.3456e9, 3.1415926535])
np.set_printoptions(suppress=True)
print(arr)


[1.000e+10 2.346e+09 3.142e+00]


In [24]:
#Exercise 23. How to limit the number of items printed in output of numpy array?
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


In [25]:
#Exercise 24. How to print the full numpy array without truncating
a = np.arange(15)
np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
#Exercise 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
sal_data = np.genfromtxt('Salaries.csv', delimiter=',', skip_header=0,usecols = [0,1,2,3,4,5], dtype = object)
print(sal_data)

[[b'rank' b'discipline' b'phd' b'service' b'sex' b'salary']
 [b'Prof' b'B' b'56' b'49' b'Male' b'186960']
 [b'Prof' b'A' b'12' b'6' b'Male' b'93000']
 ...
 [b'Prof' b'B' b'17' b'17' b'Female' b'124312']
 [b'Prof' b'A' b'28' b'14' b'Female' b'109954']
 [b'Prof' b'A' b'23' b'15' b'Female' b'109646']]


In [28]:
#Exercise 26. How to extract a particular column from 1D array of tuples?
sal_data = np.genfromtxt('Salaries.csv', delimiter=',', skip_header=1, 
                          usecols = [5], dtype = object)
print(sal_data)
array_of_tuples = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

# Extracting the second column (index 1)
column_index = 1
print(array_of_tuples[:, column_index])

[b'186960' b'93000' b'110515' ... b'124312' b'109954' b'109646']
[2 5 8]


In [29]:
#Exercise-27:How to convert a 1d array of tuples to a 2d numpy array?
array_of_tuples = np.array([(1, 2), (3, 4), (5, 6)])
two_d_array = np.array(array_of_tuples.tolist())

print("2D NumPy array:")
print(two_d_array)

2D NumPy array:
[[1 2]
 [3 4]
 [5 6]]


In [30]:
#Exercise-28:How to compute the mean, median, standard deviation of a numpy array?
arr = np.array([1, 2, 3, 4, 5])
mean, median, std_deviation = np.mean(arr), np.median(arr), np.std(arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_deviation)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [31]:
#Exercise-29:How to normalize an array so the values range exactly between 0 and 1?
arr = np.array([1, 2, 3, 4, 5])
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized array:", normalized_arr)

Normalized array: [0.   0.25 0.5  0.75 1.  ]


In [32]:
#Exercise 30. How to compute the softmax score?
def softmax(scores):
    exp_scores = np.exp(scores)
    softmax_scores = exp_scores / np.sum(exp_scores)
    return softmax_scores

scores = np.array([2.0, 1.0, 0.1])
softmax_scores = softmax(scores)
print("Softmax scores:", softmax_scores)

Softmax scores: [0.659 0.242 0.099]


In [33]:
#Exercise 31. How to find the percentile scores of a numpy array?
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
percentiles = [25, 50, 75]
percentile_scores = np.percentile(arr, percentiles)
print("Percentile scores:", percentile_scores)

Percentile scores: [3.25 5.5  7.75]


In [34]:
#Exercise 32. How to insert values at random positions in an array?
def insert_values(arr, values, num_insertions):
    indices = np.random.randint(0, len(arr), size=num_insertions)
    arr[indices] = values
    return arr

arr = np.array([1, 2, 3, 4, 5])
values = np.array([10, 20, 30])
num_insertions = 3
result = insert_values(arr, values, num_insertions)
print("Result array after insertions:", result)

Result array after insertions: [ 1 30 10  4 20]


In [35]:
#Exercise 33. How to find the position of missing values in numpy array?
arr = np.array([1, np.nan, 3, np.nan, 5])
missing_indices = np.where(np.isnan(arr))[0]
print("Positions of missing values:", missing_indices)

Positions of missing values: [1 3]


In [36]:
#Exercise 34. How to filter a numpy array based on two or more conditions?
arr = np.arange(11)

filtered_array = arr[(arr > 3) & (arr % 2 == 0)]

print("Filtered array based on conditions:", filtered_array)

Filtered array based on conditions: [ 4  6  8 10]


In [37]:
#Exercise 35. How to drop rows that contain a missing value from a numpy array?

arr = np.array([[1, 2, 3],
                [4, np.nan, 6],
                [7, 8, 9]])
arr_cleaned = arr[~np.isnan(arr).any(axis=1)]
print("Array after dropping rows with missing values:")
print(arr_cleaned)

Array after dropping rows with missing values:
[[1. 2. 3.]
 [7. 8. 9.]]


In [38]:
#Exercise 36. How to find the correlation between two columns of a numpy array?
arr = np.array([[10, 22, 43],
                [42, 53, 61],
                [7, 8, 9]])
column1 = arr[:, 0]
column2 = arr[:, 2]
correlation = np.corrcoef(column1, column2)[0, 1]
print("Correlation between the two columns:", correlation)

Correlation between the two columns: 0.8127081731060041


In [39]:
#Exercise 37. How to find if a given array has any null values?
arr = np.array([1, 2, np.nan, 4, 5])
has_null_values = np.isnan(arr).any()
print(has_null_values)

True


In [40]:
#Exercise 38. How to replace all missing values with 0 in a numpy array?
arr = np.array([1, 2, np.nan, 4, 5])
arr_without_null = np.nan_to_num(arr, nan=0)
print("Array after replacing missing values with 0:")
print(arr_without_null)

Array after replacing missing values with 0:
[1. 2. 0. 4. 5.]


In [41]:
#Exercise 39. How to find the count of unique values in a numpy array?
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_values, counts = np.unique(arr, return_counts=True)
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")

Value: 1, Count: 1
Value: 2, Count: 2
Value: 3, Count: 3
Value: 4, Count: 4


In [42]:
#Exercise 40. How to convert a numeric to a categorical (text) array?
numeric_array = np.array([1, 2, 3, 2, 1, 3, 2, 3, 1])
mapping = {1: 'Low', 2: 'Medium', 3: 'High'}
categorical_array = np.array([mapping[value] for value in numeric_array])
#np.set_printoptions(threshold=numeric_array.size)
print("Numeric array:", numeric_array)
print("Categorical array:", categorical_array)

Numeric array: [1 2 3 2 1 3 2 3 1]
Categorical array: ['Low' 'Medium' 'High' 'Medium' 'Low' 'High' 'Medium' 'High' 'Low']


In [43]:
#Exercise 41. How to create a new column from existing columns of a numpy array?
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

new_column1 = existing_array[:, 0] * 2  
new_column2 = existing_array[:, 1] ** 2 

new_array = np.column_stack((existing_array, new_column1, new_column2))

print("New array with new columns created from existing columns:")
print(new_array)

New array with new columns created from existing columns:
[[ 1  2  3  2  4]
 [ 4  5  6  8 25]
 [ 7  8  9 14 64]]


In [44]:
#Exercise 42. How to do probabilistic sampling in numpy?
array = np.array([1, 2, 3, 4, 5])
probabilities = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
sampled_values = np.random.choice(array, size=5, p=probabilities)
print("Sampled values:", sampled_values)

Sampled values: [2 2 4 2 5]


In [45]:
#Exercise 43. How to get the second largest value of an array when grouped by another array?
values = np.array([5, 8, 3, 9, 6, 7, 2, 4, 1, 10])
group = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])
unique_groups = np.unique(group)
second_largest_values = np.zeros_like(unique_groups, dtype=values.dtype)
for i, g in enumerate(unique_groups):
    group_values = values[group == g]  # Extract values for current group
    group_values_sorted = np.sort(group_values)  # Sort values in ascending order
    second_largest_values[i] = group_values_sorted[-2]  # Get second largest value

print("Second largest values for each group:", second_largest_values)

Second largest values for each group: [5 3 6 2 1]


In [46]:
#Exercise 44. How to sort a 2D array by a column
array_2d = np.array([[5, 2, 3],
                     [1, 6, 4],
                     [7, 0, 8]])

sort_column_index = 0

sorted_indices = np.argsort(array_2d[:, sort_column_index])
sorted_array_2d = array_2d[sorted_indices]

print("Sorted array by column", sort_column_index, ":\n", sorted_array_2d)

Sorted array by column 0 :
 [[1 6 4]
 [5 2 3]
 [7 0 8]]


In [47]:
#Exercise 45. How to find the most frequent value in a numpy array?
arr = np.array([1, 2, 3, 2, 2, 3, 4, 4, 4, 4])
most_frequent_value = np.argmax(np.bincount(arr))
print("Most frequent value:", most_frequent_value)

Most frequent value: 4


In [48]:
#Exercise 46. How to find the position of the first occurrence of a value greater than a given value?
arr = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 10])
given_value = 5
first_occurrence_index = np.argmax(arr > given_value)
print("Position of the first occurrence of a value greater than", given_value, ":", first_occurrence_index)

Position of the first occurrence of a value greater than 5 : 3


In [49]:
#Exercise 47. How to replace all values greater than a given value to a given cutoff?
arr = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 10])
given_value = 5
cutoff = 100
arr[arr > given_value] = cutoff
np.set_printoptions(threshold=arr.size)
print("Array after replacing values greater than", given_value, "with", cutoff, ":", arr)

Array after replacing values greater than 5 with 100 : [  1   3   5 100 100   2   4 100 100 100]


In [50]:
#Exercise 48. How to get the positions of top n values from a numpy array?
arr = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])
n = 3
top_n_indices = np.argsort(arr)[-n:]
print("Positions of top", n, "values:", top_n_indices)

Positions of top 3 values: [6 2 4]


In [51]:
#Exercise 49. How to compute the row wise counts of all possible values in an array?
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

np.random.seed(100)
np.set_printoptions(threshold=10)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[[ 9  9  4 ...  3  6  3]
 [ 3  3  2 ... 10  7  3]
 [ 5  2  6 ...  8  2  2]
 [ 8  8  1 ...  3  6  9]
 [ 2  1  8 ...  3  6  2]
 [ 9  2  6 ...  6  1 10]]
[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [52]:
#Exercise 50. How to convert an array of arrays into a flat 1d array?
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

arr_2d = np.concatenate([arr1, arr2, arr3])
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
#EXERCISE 51: How to get the n largest values of an array ?
arr = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])
n = 3
largest_values = np.sort(arr)[-n:][::-1]
print("The", n, "largest values:", largest_values)

The 3 largest values: [9 8 7]


In [59]:
#52.Given an arbitrary number of vectors, build the cartesian product (every combinations of every item).
vector1 = np.array([1, 2])
vector2 = np.array(['a', 'b', 'c'])
vector3 = np.array([True, False])
cartesian_product = list((vector1, vector2, vector3))
print(cartesian_product)

[array([1, 2]), array(['a', 'b', 'c'], dtype='<U1'), array([ True, False])]


In [60]:
# 53.Build the cartesian product
mesh = np.array(np.meshgrid(vector1, vector2, vector3)).T.reshape(-1, 3)

print("Cartesian product:")
print(mesh)

Cartesian product:
[['1' 'a' 'True']
 ['1' 'b' 'True']
 ['1' 'c' 'True']
 ...
 ['2' 'a' 'False']
 ['2' 'b' 'False']
 ['2' 'c' 'False']]


In [61]:
#54.Consider a 16x16 array, how to get the blocksum (block size is 4x4)?
arr = np.random.randint(1, 10, size=(16, 16))

block_size = 4

block_sums = np.zeros((16-block_size+1, 16-block_size+1))

for i in range(16-block_size+1):
    for j in range(16-block_size+1):
        block = arr[i:i+block_size, j:j+block_size]
        block_sums[i, j] = np.sum(block)

print("Block sums:")
print(block_sums)

Block sums:
[[ 76.  93.  89. ...  91.  90.  80.]
 [ 73.  87.  84. ...  87.  88.  75.]
 [ 68.  77.  84. ...  83.  85.  79.]
 ...
 [101.  95.  88. ...  80.  84.  78.]
 [ 97.  91.  79. ...  76.  86.  84.]
 [ 86.  82.  72. ...  89.  94.  88.]]


In [62]:
#55.Compute a matrix rank.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rank = np.linalg.matrix_rank(matrix)
print("Rank of the matrix:", rank)

Rank of the matrix: 2


In [63]:
#56.How to find the most frequent value in an array?
arr = np.array([1, 2, 3, 2, 2, 3, 4, 4, 4, 4])

most_frequent_value = np.argmax(np.bincount(arr))

print("Most frequent value:", most_frequent_value)

Most frequent value: 4


In [64]:
#57.Extract all the contiguous 3x3 blocks from a random 10x10 matrix.
matrix = np.random.randint(0, 10, size=(10, 10))
blocks = []
for i in range(8):
    for j in range(8):
        block = matrix[i:i+3, j:j+3]
        blocks.append(block)
blocks_array = np.array(blocks)

print("Contiguous 3x3 blocks:")
print(blocks_array)

Contiguous 3x3 blocks:
[[[0 9 1]
  [6 6 3]
  [7 1 2]]

 [[9 1 4]
  [6 3 3]
  [1 2 8]]

 [[1 4 3]
  [3 3 3]
  [2 8 3]]

 ...

 [[7 1 1]
  [2 0 3]
  [4 9 6]]

 [[1 1 7]
  [0 3 7]
  [9 6 5]]

 [[1 7 8]
  [3 7 4]
  [6 5 4]]]
