In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
np.__version__

'1.24.3'

In [15]:
#create 1D array using numpy
a=np.array([1,2,3,4,5,6,7])

In [18]:
print(a)

[1 2 3 4 5 6 7]


In [20]:
a.ndim

1

In [21]:
a.shape

(7,)

In [22]:
#create a 2D array
b=np.array([[1,2,3,4,5,6,7,8]])

In [23]:
print(a)

[1 2 3 4 5 6 7]


In [24]:
b.ndim

2

In [25]:
b.shape


(1, 8)

In [26]:
c=np.array([[1,2,3,4],[5,6,7,8]])#2D array having 2 rows and 4 colums

In [27]:
c.shape

(2, 4)

In [28]:
#create a 3D array
d=np.array([[[1,2,3,4,5,6,7,8,9]]])

In [30]:
d.shape

(1, 1, 9)

In [43]:
#3D array having (2,3,4)
e=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]],[[7,8,9,10],[1,2,3,4],[4,5,6,7]]])
print(e)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]

 [[ 7  8  9 10]
  [ 1  2  3  4]
  [ 4  5  6  7]]]


In [44]:
e.shape


(2, 3, 4)

In [38]:
a1=np.array(["kiit","1",True,9+6j])
print(a1)

['kiit' '1' 'True' '(9+6j)']


In [45]:
#find the sum of element in row wise and column wise
e.sum()


132

In [46]:
e.sum(axis=0)

array([[ 8, 10, 12, 14],
       [ 5,  7,  9, 11],
       [11, 13, 15, 17]])

In [47]:
e.sum(axis=1)

array([[12, 15, 18, 21],
       [12, 15, 18, 21]])

In [48]:
a2=np.array([[12,-90,0,4],[23,-76,24,36],[1,55,-23,6]])
print(a2)

[[ 12 -90   0   4]
 [ 23 -76  24  36]
 [  1  55 -23   6]]


In [49]:
a2.sum(axis=0)

array([  36, -111,    1,   46])

In [50]:
a2.sum(axis=1)

array([-74,   7,  39])

In [52]:
a2.min()

-90

In [53]:
a2.max()

55

In [54]:
a2.mean()

-2.3333333333333335

In [55]:
#find the location of min element
a2.argmin()

1

In [56]:
#find the location of max element
a2.argmax()

9

In [58]:
#create a zero matrix
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [60]:
type(z),a2.dtype#dtype means what is inside the data type 

(numpy.ndarray, dtype('int32'))

In [61]:
z.dtype

dtype('float64')

In [62]:
type(a2),a2.dtype

(numpy.ndarray, dtype('int32'))

In [64]:
z1=np.zeros((2,3),dtype=int)
print(z1)

[[0 0 0]
 [0 0 0]]


In [66]:
#ones matrix
z2=np.ones(3)
print(z2)

[1. 1. 1.]


In [67]:
z3=np.ones((2,3),dtype=int)
print(z3)

[[1 1 1]
 [1 1 1]]


In [69]:
n1=z3*5
print(n1)

[[5 5 5]
 [5 5 5]]


In [71]:
#identity matrix
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [72]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [76]:
#create with random number
np.random.rand(8)

array([0.05454355, 0.52354971, 0.71927685, 0.69555225, 0.67302388,
       0.05083445, 0.51490185, 0.41889195])

In [79]:
np.random.randint(8)

3

In [83]:
np.linspace(10,2)#equal distribution linear space

array([10.        ,  9.83673469,  9.67346939,  9.51020408,  9.34693878,
        9.18367347,  9.02040816,  8.85714286,  8.69387755,  8.53061224,
        8.36734694,  8.20408163,  8.04081633,  7.87755102,  7.71428571,
        7.55102041,  7.3877551 ,  7.2244898 ,  7.06122449,  6.89795918,
        6.73469388,  6.57142857,  6.40816327,  6.24489796,  6.08163265,
        5.91836735,  5.75510204,  5.59183673,  5.42857143,  5.26530612,
        5.10204082,  4.93877551,  4.7755102 ,  4.6122449 ,  4.44897959,
        4.28571429,  4.12244898,  3.95918367,  3.79591837,  3.63265306,
        3.46938776,  3.30612245,  3.14285714,  2.97959184,  2.81632653,
        2.65306122,  2.48979592,  2.32653061,  2.16326531,  2.        ])

In [84]:
#Exercise 1. Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.24.3


In [85]:
#Exercise 2. How to create a 1D array?
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
#Exercise 3. How to create a boolean array?
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [96]:
#Exercise 4. How to extract items that satisfy a given condition from 1D array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [95]:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [94]:
#Exercise 7. How to reshape an array?
np.arange(10)
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [97]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

In [1]:
import matpoltlib.pyplot as pit

ModuleNotFoundError: No module named 'matpoltlib'